[package]
name = "commons"
version.workspace = true
edition.workspace = true

[dependencies.serde]
workspace = true
features = ["rc", "derive"]

[dependencies.regex]
workspace = true

[dependencies.once_cell]
workspace = true
features = ["std"]
